version: '3'
services:
  adonis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PORT}
      APP_KEY: ${APP_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
      HOST: ${HOST}
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - shared-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

  python:
    build:
      context: ./python
    container_name: python
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    driver: bridge
