# Use a lightweight base image
FROM debian:latest

# Install only the necessary parts of LibreOffice
RUN apt-get update --fix-missing && \
    apt-get install -y libreoffice-writer

# Add the entrypoint for running in headless mode
ENTRYPOINT ["libreoffice", "--headless", "--accept=socket,host=0.0.0.0,port=8100;urp;", "--nofirststartwizard"]
